//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingRecommendationSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpSysResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpSysResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HousingRecommendationSystem.Resources.ExpSysResources", typeof(ExpSysResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 25 years old.
        /// </summary>
        internal static string ac1 {
            get {
                return ResourceManager.GetString("ac1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 to 30 years old.
        /// </summary>
        internal static string ac2 {
            get {
                return ResourceManager.GetString("ac2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31 to 34 years old.
        /// </summary>
        internal static string ac3 {
            get {
                return ResourceManager.GetString("ac3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35 to 40 years old.
        /// </summary>
        internal static string ac4 {
            get {
                return ResourceManager.GetString("ac4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 to 50 years old.
        /// </summary>
        internal static string ac5 {
            get {
                return ResourceManager.GetString("ac5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51 and above.
        /// </summary>
        internal static string ac6 {
            get {
                return ResourceManager.GetString("ac6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How old are you?.
        /// </summary>
        internal static string age_question {
            get {
                return ResourceManager.GetString("age_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 200k.
        /// </summary>
        internal static string bb01 {
            get {
                return ResourceManager.GetString("bb01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200k - 299k.
        /// </summary>
        internal static string bb02 {
            get {
                return ResourceManager.GetString("bb02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300k - 399k.
        /// </summary>
        internal static string bb03 {
            get {
                return ResourceManager.GetString("bb03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400k - 499k.
        /// </summary>
        internal static string bb04 {
            get {
                return ResourceManager.GetString("bb04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500k - 599k.
        /// </summary>
        internal static string bb05 {
            get {
                return ResourceManager.GetString("bb05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600k - 699k.
        /// </summary>
        internal static string bb06 {
            get {
                return ResourceManager.GetString("bb06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700k - 799k.
        /// </summary>
        internal static string bb07 {
            get {
                return ResourceManager.GetString("bb07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800k - 899k.
        /// </summary>
        internal static string bb08 {
            get {
                return ResourceManager.GetString("bb08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 900k - 999k.
        /// </summary>
        internal static string bb09 {
            get {
                return ResourceManager.GetString("bb09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.00 Million - 1.49 Million.
        /// </summary>
        internal static string bb10 {
            get {
                return ResourceManager.GetString("bb10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.50 Million - 1.99 Million.
        /// </summary>
        internal static string bb11 {
            get {
                return ResourceManager.GetString("bb11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.00 Million - 2.49 Million.
        /// </summary>
        internal static string bb12 {
            get {
                return ResourceManager.GetString("bb12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.50 Million - 2.99 Million.
        /// </summary>
        internal static string bb13 {
            get {
                return ResourceManager.GetString("bb13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.00 Million - 3.49 Million.
        /// </summary>
        internal static string bb14 {
            get {
                return ResourceManager.GetString("bb14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.50 Million - 3.99 Million.
        /// </summary>
        internal static string bb15 {
            get {
                return ResourceManager.GetString("bb15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.00 Million - 4.49 Million.
        /// </summary>
        internal static string bb16 {
            get {
                return ResourceManager.GetString("bb16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.50 Million - 4.99 Million.
        /// </summary>
        internal static string bb17 {
            get {
                return ResourceManager.GetString("bb17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.00 Million and above.
        /// </summary>
        internal static string bb18 {
            get {
                return ResourceManager.GetString("bb18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least how many bedroom/s are you interested?.
        /// </summary>
        internal static string bedroom_qn {
            get {
                return ResourceManager.GetString("bedroom_qn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much is your budget?.
        /// </summary>
        internal static string budget {
            get {
                return ResourceManager.GetString("budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this your first time buying a house?.
        /// </summary>
        internal static string buyer_exp {
            get {
                return ResourceManager.GetString("buyer_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you own a car?.
        /// </summary>
        internal static string car_qn {
            get {
                return ResourceManager.GetString("car_qn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your current citizenship?.
        /// </summary>
        internal static string citizenship {
            get {
                return ResourceManager.GetString("citizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any children?.
        /// </summary>
        internal static string family_qn {
            get {
                return ResourceManager.GetString("family_qn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreigner.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string hh1 {
            get {
                return ResourceManager.GetString("hh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequent.
        /// </summary>
        internal static string hh2 {
            get {
                return ResourceManager.GetString("hh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string hh3 {
            get {
                return ResourceManager.GetString("hh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrequent.
        /// </summary>
        internal static string hh4 {
            get {
                return ResourceManager.GetString("hh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often do you do housework?.
        /// </summary>
        internal static string housework_qn {
            get {
                return ResourceManager.GetString("housework_qn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        internal static string ll01 {
            get {
                return ResourceManager.GetString("ll01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North East.
        /// </summary>
        internal static string ll02 {
            get {
                return ResourceManager.GetString("ll02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        internal static string ll03 {
            get {
                return ResourceManager.GetString("ll03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        internal static string ll04 {
            get {
                return ResourceManager.GetString("ll04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central.
        /// </summary>
        internal static string ll05 {
            get {
                return ResourceManager.GetString("ll05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is your preferred location?.
        /// </summary>
        internal static string location_qn {
            get {
                return ResourceManager.GetString("location_qn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any maids?.
        /// </summary>
        internal static string maid_qn {
            get {
                return ResourceManager.GetString("maid_qn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you married?.
        /// </summary>
        internal static string marital_status {
            get {
                return ResourceManager.GetString("marital_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string mm1 {
            get {
                return ResourceManager.GetString("mm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string mm2 {
            get {
                return ResourceManager.GetString("mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Resident.
        /// </summary>
        internal static string pr {
            get {
                return ResourceManager.GetString("pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 3 years.
        /// </summary>
        internal static string prr1 {
            get {
                return ResourceManager.GetString("prr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 years and more.
        /// </summary>
        internal static string prr2 {
            get {
                return ResourceManager.GetString("prr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long have you been living in Singapore?.
        /// </summary>
        internal static string residency {
            get {
                return ResourceManager.GetString("residency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 room.
        /// </summary>
        internal static string rr1 {
            get {
                return ResourceManager.GetString("rr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 rooms.
        /// </summary>
        internal static string rr2 {
            get {
                return ResourceManager.GetString("rr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 rooms.
        /// </summary>
        internal static string rr3 {
            get {
                return ResourceManager.GetString("rr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 rooms.
        /// </summary>
        internal static string rr4 {
            get {
                return ResourceManager.GetString("rr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 rooms.
        /// </summary>
        internal static string rr5 {
            get {
                return ResourceManager.GetString("rr5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 5 Rooms.
        /// </summary>
        internal static string rr6 {
            get {
                return ResourceManager.GetString("rr6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singaporean.
        /// </summary>
        internal static string sc {
            get {
                return ResourceManager.GetString("sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you plan to get married in the near future?.
        /// </summary>
        internal static string single_qn {
            get {
                return ResourceManager.GetString("single_qn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you prefer racquet sport or basketball sport? (Neither if both are not in preferences).
        /// </summary>
        internal static string sport_gen {
            get {
                return ResourceManager.GetString("sport_gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhaps, you like to jog, gym or swim?.
        /// </summary>
        internal static string sport_gym {
            get {
                return ResourceManager.GetString("sport_gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then, do you play badminton, squash or tennis?.
        /// </summary>
        internal static string sport_racket {
            get {
                return ResourceManager.GetString("sport_racket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your spouse citizenship?.
        /// </summary>
        internal static string spouse_citizenship {
            get {
                return ResourceManager.GetString("spouse_citizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has your spouse obtained his/her Singapore Permanent Residence for more than 3 years?.
        /// </summary>
        internal static string spouse_residency {
            get {
                return ResourceManager.GetString("spouse_residency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racquet Sport.
        /// </summary>
        internal static string ss1 {
            get {
                return ResourceManager.GetString("ss1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basketball.
        /// </summary>
        internal static string ss2 {
            get {
                return ResourceManager.GetString("ss2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither.
        /// </summary>
        internal static string ss3 {
            get {
                return ResourceManager.GetString("ss3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badminton.
        /// </summary>
        internal static string ss4 {
            get {
                return ResourceManager.GetString("ss4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squash.
        /// </summary>
        internal static string ss5 {
            get {
                return ResourceManager.GetString("ss5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis.
        /// </summary>
        internal static string ss6 {
            get {
                return ResourceManager.GetString("ss6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogging.
        /// </summary>
        internal static string ss7 {
            get {
                return ResourceManager.GetString("ss7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym.
        /// </summary>
        internal static string ss8 {
            get {
                return ResourceManager.GetString("ss8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        internal static string ss9 {
            get {
                return ResourceManager.GetString("ss9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the House Recommendation Expert System..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you mind an older estate? (Year of Completion &gt; 15 years).
        /// </summary>
        internal static string yr_complete {
            get {
                return ResourceManager.GetString("yr_complete", resourceCulture);
            }
        }
    }
}
